repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.0.4
        hooks:
              - id: isort
      - repo: https://github.com/ambv/black
        rev: stable
        hooks:
              - id: black
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.1
        hooks:
              - id: flake8
                alias: flake8
                name: flake8
                args: ["--config=python/.flake8"]
                types: [python]
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.1
        hooks:
              - id: flake8
                alias: flake8-cython
                name: flake8-cython
                args: ["--config=python/.flake8.cython"]
                types: [cython]
default_language_version:
      python: python3
